version: '3.8'

services:
  dag-builder-db:
    image: postgres:16-alpine
    container_name: dag-builder-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: dag-builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dag_data:/var/lib/postgresql/data

  log-ingestion-db:
    image: postgres:16-alpine
    container_name: log-ingestion-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: log-ingestion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - log_data:/var/lib/postgresql/data

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-network # Ensure this is part of the same network

networks:
  kafka-network: # Define a custom network
    driver: bridge

volumes:
  dag_data:
  log_data:
  kafka_data:
